COLUMNS:
  trans_date_trans_time: object
  cc_num: int64
  merchant: object
  category: object
  amt: float64
  first: object
  last: object
  gender: object
  street: object
  city: object
  state: object
  zip: int64
  lat: float64
  long: float64
  city_pop: int64
  job: object
  dob: object
  trans_num: object
  unix_time: int64
  merch_lat: float64
  merch_long: float64
  is_fraud: int64

TARGET_COLUMN: is_fraud
